[env:esp32-s3-devkitc-1-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 921600
upload_speed = 921600

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 16MB
board_build.partitions = partitions_16mb_lfs.csv
board_build.filesystem = littlefs

build_unflags =
  -Os

build_flags =
  -O2
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1

build_src_flags =
  -Wall
  -Wextra
  -Wformat=2
  -Wno-format-nonliteral
  -Wno-unused-parameter

lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  adafruit/Adafruit LSM6DS @ ^4.7.4
  adafruit/Adafruit BMP280 Library @ ^2.6.8
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit BusIO @ ^1.14.1
  https://github.com/ESP32Async/AsyncTCP.git
  https://github.com/ESP32Async/ESPAsyncWebServer.git
